# Generated by Django 4.2.13 on 2024-07-08 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='StudentApp.program')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_level', models.CharField(choices=[('Bac+3', 'Bac+3'), ('Bac+4', 'Bac+4'), ('Bac+5', 'Bac+5'), ('Bac+6', 'Bac+6'), ('Bac+7', 'Bac+7')], max_length=5, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='student_photos/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='student_cvs/')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='StudentApp.program')),
                ('related_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.subject')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='StudentApp.school')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='StudentApp.school'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('equity', "Parts d'entreprise")], max_length=6, null=True)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equity_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='StudentApp.company')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.specialty')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('mission_title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('moderated', 'Moderated')], default='visible', max_length=20)),
                ('moderation_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='StudentApp.student')),
            ],
        ),
    ]
