# Generated by Django 5.0.6 on 2024-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_remove_mission_cash_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mission',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'argent'), ('equity', "Parts d'entreprise")], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(),
        ),
    ]
