# Generated by Django 5.0.6 on 2024-07-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_article_alter_mission_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='cash_amount_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='cash_amount_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='equity_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
