# Generated by Django 5.0.6 on 2024-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_mission_cash_amount_max_mission_cash_amount_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
