# Generated by Django 5.0.6 on 2024-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0007_mission_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificat',
            field=models.FileField(blank=True, null=True, upload_to='student_cvs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
