# Generated by Django 5.0.6 on 2024-07-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0008_student_certificat_student_portfolio_link'),
        ('StudentApp', '0009_alter_program_name_alter_subject_name'),
    ]

    operations = [
    ]
