# Generated by Django 5.0.6 on 2024-08-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0011_remove_student_certificat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Rénumération'), ('equity', "Parts d'entreprise")], max_length=6, null=True),
        ),
    ]
