# Generated by Django 5.0.6 on 2024-08-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0012_alter_mission_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
