# Generated by Django 5.0.6 on 2024-08-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0013_company_first_name_company_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(),
        ),
    ]
